version: "3.4"

services:
  postgres:
    container_name: demo_postgres
    image: "clkao/postgres-plv8:12-2"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "password"
      PGDATA: "/data/postgres"
    volumes:
       - postgres:/data/postgres
    ports:
      - "15432:5432"
    restart: unless-stopped
  pgadmin:
    container_name: demo_pgadmin
    image: "dpage/pgadmin4:6.4"
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@svtrobotics.com"
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
    volumes:
       - pgadmin:/var/lib/pgadmin
       - ./docker-pgadmin-servers.json:/pgadmin4/servers.json
    ports:
      - "15433:80"
    entrypoint:
      - "/bin/sh"
      - "-c"
      - "/bin/echo 'postgres:5432:*:postgres:password' > /tmp/pgpassfile && chmod 600 /tmp/pgpassfile && /entrypoint.sh"
    restart: unless-stopped
  dotnet:
    container_name: demo_be
    image: local/wfe
    environment:
      ConfigurationSettings__PostgresConnectionString: "Host=postgres;Username=postgres;Password=password;Database=postgres"
      ASPNETCORE_ENVIRONMENT: "QA"
      AzureAdB2C__ClientId: "077c8a1e-47c9-431c-ba6e-8e0f1f2367b9"
      ASPNETCORE_URLS: "http://+:80"
    volumes:
      - dotnet:/root/.aspnet/DataProtection-Keys
    ports:
     - "80:80"
    depends_on:
      - postgres
  sveltekit:
    container_name: demo_fe
    image: "local/svelte-wfe"
    environment:
      WORKFLOW_ENGINE_BASE_URL_SERVER: "http://dotnet/"
      WORKFLOW_ENGINE_BASE_URL_CLIENT: "https://localhost:5000/"
    depends_on:
      - dotnet
  nginx:
    container_name: demo_reverse_proxy
    image: "nginx"
    volumes:
      - ./reverse-proxy.conf:/etc/nginx/conf.d/reverse-proxy.conf
      - ./certs:/etc/ssl
    ports:
      - "5001:443"
      - "5000:5000"
    depends_on:
      - sveltekit

volumes:
  pgadmin:
  postgres:
  dotnet:

